import fs from "node:fs";
// Full commitment and canonical case schema are verified before assignment.
import crypto from "node:crypto";
import { CalldataAddress } from "genlayer-js/types";
const A="0xfDB7f4C28F157662133dF51B5a864BDa3F4B7060", C=61997, CLAIM="refundbot-v1-claim-live-sf1", CHALLENGE="refundbot-v1-challenge-live-sf1", EXECUTOR="0xd6423ae82a975d55c6ceac222827a727325e0459", POLICY="0941213cf36dcb58422ea2f43d710f1249f715d1de8fe2d77b90ece252de4f19", RISK="8e3e4d4f442675771bab7b8bd5cb31f77e83683eed025be25bcce4593a3171c7", RUBRIC="7bd435d7166ab72a3477ead47588be5359b40bd9aaa7c11b87212b50b4947f70", EXPECTED="426b4b9a5a5a2e794f684ccc7fcdb1e6b4d50d1cd7c06973c6957e069c06b10d";
const ad=x=>new CalldataAddress(Uint8Array.from(x.slice(2).match(/../g).map(h=>parseInt(h,16))));
const canonical=v=>JSON.stringify(v,(k,x)=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.keys(x).sort().map(i=>[i,x[i]])):x).replace(/[^\x00-\x7F]/g,c=>`\\u${c.charCodeAt(0).toString(16).padStart(4,"0")}`);
const digest=v=>crypto.createHash("sha256").update(canonical(v)).digest("hex");
const cases=JSON.parse(fs.readFileSync("harness/challenges/refund-policy-v4.2/cases.json","utf8"));
const commitment=()=>digest({cases,policy_hash:POLICY,risk_policy_hash:RISK,rubric_hash:RUBRIC});
export default async function run(c){if(process.env.RUN_APTERRA_ASSIGN_SF1!=="1")throw Error("SET_RUN_APTERRA_ASSIGN_SF1");if(Number(c.chain?.id)!==C)throw Error("WRONG_CHAIN");const sender=typeof c.account==="string"?c.account.toLowerCase():String(c.account?.address??"").toLowerCase();if(sender!==EXECUTOR)throw Error("WRONG_SIGNER");const claim=JSON.parse(await c.readContract({address:A,functionName:"get_claim",args:[CLAIM]}));if(claim.state!=="CLAIMED")throw Error("CLAIM_NOT_CLAIMED");try{const x=await c.readContract({address:A,functionName:"get_challenge",args:[CLAIM]});if(x)throw Error("CHALLENGE_EXISTS")}catch(e){if(e.message==="CHALLENGE_EXISTS")throw e}const full=commitment();if(full!==EXPECTED)throw Error(`COMMITMENT_DRIFT:${full}`);const args=[CLAIM,CHALLENGE,RUBRIC,ad(EXECUTOR),full],e=await c.estimateTransactionFees({});if(!e.distribution||BigInt(e.feeValue??0)<=0n)throw Error("ZERO_FEE");const tx=await c.writeContract({address:A,functionName:"assign_challenge",args,value:0n,fees:{distribution:e.distribution,...(e.messageAllocations?.length?{messageAllocations:e.messageAllocations}:{}),feeValue:e.feeValue}});console.log(`ASSIGN_CHALLENGE_SF1_TX=${tx}`);const r=await c.waitForTransactionReceipt({hash:tx,waitUntil:"decided",fullTransaction:true,retries:120,interval:5000});if(!["ACCEPTED","FINALIZED"].includes(r.statusName)||r.txExecutionResultName!=="FINISHED_WITH_RETURN")throw Error("ASSIGN_FAILED");const out=JSON.parse(await c.readContract({address:A,functionName:"get_challenge",args:[CLAIM]}));if(out.id!==CHALLENGE||out.status!=="ASSIGNED_NOT_REVEALED"||out.case_inputs_hash!==EXPECTED)throw Error("ASSIGN_READBACK_MISMATCH");console.log("STEP_VERIFIED=true");}
